services:
- postgresql
language: ruby
rvm:
- 2.4.1
script:
- bundle install
- bundle exec rails db:reset db:setup db:migrate RAINS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: vIbRSgSavPagfzagGXPJzuLKAgLJuZBIRb8K6LBjfr61YOuYGs9rBK5RIKRGrgdKa5S/iOwxygYLWuzMvqmj3wzifp2mK4XmE1m5UkLnTNbm7Lqum5DWreKRiHPJqVQ/JhmFGYqmc0akqzzWk7Sf3Sv+bQlmOHG4Sj9oWGyS1mrod++uBKphb6lB0mjIHZAe+ZMSMDK7cjO26oWXPlXPWVzqh3Tm4+az62aRbukdJtI69mV7O0tbe1rZwN5Vlaqoqv5npo0RpKJpMFtxa8XUyx+fPwijD8/SHUJ2YQdM57IcmsR7hjP7Cpfq9/+5VSU1CHzOYIloLgY3Uc3uP889vgVwJZxxpuFJfc01Rjg9GSmpq8UEQiNNiZ04bjz1FnFN3XwWEGYpHdWDcXcJQ/qDwsgF2we9E0h2XzboSnrsihrSMGq8GvCfiFnz6HIfT5Z0IEadIYK7KvrzKcAY8YXqCssfVe0DWtTZUd9ty7kHiV5CTZG8vocvOLmZ7wMdSpCTU8KueepRF4carO1HXWS7marlOk+LAPgzW5QxHc+KuPEuLeNzNDol1tstvWPE3g1U/fDzQK4h4HnTv32HXzqouOjZc5yKcyQsHbW/eytG3vHKak30ypkKEMZtnfSj9Vu7q0Vjbqtvd1Jg6l/xBpd4Bth+HhDFPXuCpfkI8g1vKN4=
  on:
    repo: leiyakenney/sweater-weather
